name: massiv-CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]

defaults: { run: { shell: bash } }



jobs:
  tests:
    name: CI
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        resolver: [nightly, lts-17, lts-16, lts-14, lts-12]
        include:
          - resolver: lts-12
            ghc: 8.4.4
            stack-yaml: stack-extra-deps.yaml
          - resolver: lts-14
            stack-yaml: stack-extra-deps.yaml
          - resolver: lts-16
            ghc: 8.8.4
            stack-yaml: stack-extra-deps.yaml
          - resolver: lts-18
            ghc: 8.10.4

          # Latest stable for MacOS: ghc-8.8.4
          - resolver: lts-16
            os: macos-latest
            stack-yaml: stack-extra-deps.yaml
          # Latest stable for Windows: ghc-8.6.4
          - resolver: lts-14
            os: windows-latest
            stack-yaml: stack-extra-deps.yaml

    env:
      STACK_YAML: stack.yaml
      STACK_ARGS: '--resolver ${{ matrix.resolver }}'
      cache-version: v5 # bump up this version to invalidate currently stored cache
    steps:
    - uses: actions/checkout@v2

    - name: Cache
      id: cache
      uses: actions/cache@v2
      if: matrix.os != 'macos-latest'
      with:
        path: |
          ~/.stack
          .stack-work
          massiv/.stack-work
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ env.cache-version }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.resolver }}-${{ env.cache-version }}
    - name: Cache
      id: cache-macos
      uses: actions/cache@v2
      if: matrix.os == 'macos-latest'
      with:
        path: |
          ~/.stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-${{ env.cache-version }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.resolver }}-${{ env.cache-version }}
    - name: Workaround setup-exe-cache failure on macos
      if: steps.cache-macos.outputs.cache-hit == 'true' && matrix.os == 'macos-latest'
      run: |
        rm -r ~/.stack/setup-exe-cache
    - name: Windows Cache
      id: cache-windows
      uses: actions/cache@v2
      if: matrix.os == 'windows-latest'
      with:
        path: |
          C:\\Users\\RUNNER~1\\AppData\\Roaming\\stack
          C:\\Users\\RUNNER~1\\AppData\\Local\\Programs\\stack
        key: ${{ runner.os }}-${{ matrix.resolver }}-programs-${{ env.cache-version }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.resolver }}-programs-${{ env.cache-version }}

    - name: Ubuntu install GHC
      if: matrix.ghc != '' && matrix.os == 'ubuntu-latest'
      run: |
        sudo add-apt-repository ppa:hvr/ghc -y
        sudo apt-get update
        sudo apt-get install ghc-${{ matrix.ghc }}
    - name: Install Stack and local GHC
      run: |
        set -ex
        curl -sSL https://get.haskellstack.org/ | sh -s - -f
        curl -sSL https://raw.githubusercontent.com/lehins/utils/786c3fe7e9e1345d7b403019f52e344627224edf/haskell/git-modtime/git-modtime.hs -o git-modtime.hs
        [ -n "${{ matrix.ghc }}" ] && [ "${{ matrix.os }}" == "ubuntu-latest" ] && STACK_ARGS="$STACK_ARGS --system-ghc"
        [ -n "${{ matrix.stack-yaml }}" ] && STACK_YAML=${{ matrix.stack-yaml }}
        stack $STACK_ARGS runghc git-modtime.hs
    - name: Tests
      env:
        COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
      run: |
        set -ex
        [ -n "${{ matrix.ghc }}" ] && [ "${{ matrix.os }}" == "ubuntu-latest" ] && STACK_ARGS="$STACK_ARGS --system-ghc"
        [ -n "${{ matrix.stack-yaml }}" ] && STACK_YAML=${{ matrix.stack-yaml }}
        if [ "${{ matrix.os }}.${{ matrix.resolver }}" == "ubuntu-latest.lts-14" ] && [ -n "${COVERALLS_TOKEN}" ]; then
          stack $STACK_ARGS test massiv-test:tests --coverage --haddock --no-haddock-deps
          stack $STACK_ARGS hpc report --all
          curl -L https://github.com/rubik/stack-hpc-coveralls/releases/download/v0.0.6.1/shc-linux-x64-8.8.4.tar.bz2 | tar xj shc
          ./shc --repo-token="$COVERALLS_TOKEN" --partial-coverage --fetch-coverage combined custom
        else
          stack $STACK_ARGS test massiv-test:tests massiv:doctests --bench --no-run-benchmarks --haddock --no-haddock-deps
        fi

  massiv-examples:

    runs-on: ubuntu-latest

    env:
      STACK_ARGS: '--resolver lts-16.31'
    steps:
    - uses: actions/checkout@v2

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_ACTOR}/${GITHUB_REF#refs/heads/})"
      id: extract_branch

    - name: Cache
      uses: actions/cache@v2.0.0
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: |
          "~/.stack"
          "massiv-examples/.stack-work"
          "massiv-examples/*/.stack-work"
        # An explicit key for restoring and saving the cache
        key: "${{ steps.extract_branch.outputs.branch }}"
        restore-keys: "*/master"

    - name: Build and Test
      run: |
        sudo apt-get install freeglut3-dev
        cd massiv-examples
        curl -sSL https://get.haskellstack.org/ | sh -s - -f
        curl -sSL https://raw.githubusercontent.com/lehins/utils/786c3fe7e9e1345d7b403019f52e344627224edf/haskell/git-modtime/git-modtime.hs -o git-modtime.hs
        stack script $STACK_ARGS git-modtime.hs
        stack test $STACK_ARGS --bench --no-run-benchmarks --haddock --no-haddock-deps
